### ISSUE TITLE
player_hasitem Placeholder issue

### ISSUE THREAD

**Issue by rowan-smith** [PlaceholderAPI/Player-Expansion#2]
https://www.spigotmc.org/threads/need-help-with-deluxemenus.329656/
https://www.spigotmc.org/wiki/placeholderapi-placeholders/#player-placeholders

I believe there is an issue with the **%player_hasitem-mat:<MATERIAL>-amt:<amount>-data:<data value>%** placeholder. I covered the issue in the thread I linked above <3

**Comment by Gaby-TM** [comment]
Try the **checkitem** expansion:
```
%checkitem_mat:<material>%
%checkitem_mat:STONE,amt:10,data:3%
%checkitem_mat:<material>,nameequals:&cname%
%checkitem_namecontains:&cname%
%checkitem_namestartswith:&cn%
```

**Comment by Andre601** [comment]
Is this issue still a thing or can it be closed?
