### ISSUE TITLE
[Request] New player expansion placeholder suggestion

### ISSUE THREAD

**Issue by Frcsty** [PlaceholderAPI/Player-Expansion#25]
Would be nice if the placeholder that currently already exists for offhand could be made for main hand aswell (%player_item_in_offhand_level_<enchantment>%).

**Comment by aBo0oDyy** [comment]
Hey there,
The placeholder already exist, just not in the wiki or in the cloud.
I've just added it and all the other missing item in hand related placeholder in the wiki and in the cloud.
Thanks for suggesting and letting us know 😄
