### ISSUE TITLE
Bugged Player Placeholders

### ISSUE THREAD

**Issue by BloodshotPico** [PlaceholderAPI/Player-Expansion#26]
Spigot 1.14.3 (Spigot 5e4e7f32349feb)
PlaceholderAPI 2.10.3

### Issue
> What is the issue? Describe it like you would tell a friend.
Basically when using the Player expansion placeholders, namely %player_time%, %player_timestamp% and %player_biome% they don't act as intended. And after testing these 3 different player placeholders I'm guessing all of these are broken.

### Expected behaviour
> What should PlaceholderAPI do?
It should give the corresponding information for those placeholders.

### Actual behaviour
> What does PlaceholderAPI actually do?
It just prints out the placeholder names instead of their intended output.

### How to reproduce
> What steps did you made, to get this bug?
1. I used it in ChatControl Pro.
2. Downloaded the expansion.
3. Reloaded PAPI.
4. Restarted Server.
5. Does not show what they're supposed to.

**Comment by Funny-cube** [comment]
@aBo0oDyy wanna take a look at this?

**Comment by aBo0oDyy** [comment]
Taking a look into it atm
and btw `%player_timestamp% ` isnt a placeholder, will have to remove it from the wiki.

**Comment by aBo0oDyy** [comment]
They are working fine for me?
as i mentioned, `%player_timestamp%` isn't a placeholder, but the other placeholders (`%player_time%` and `%player_biome%`) are working fine.
Make sure you have Player expansion by checking if its in `/papi list`
if you didn't see it in the list, download it again:
```
/papi ecloud download Player
/papi reload
```
check the console if you get any errors, if there isn't any, try the placeholders using PAPI's parse command `/papi parse me %PlaceholderHere%`
if it worked in the parse command, my guess then its ChatControl.

**Comment by BloodshotPico** [comment]
It's ChatControl apparently placeholders are broke with it right now however they worked in some cases, and since the other placeholder I reported got removed by spigot I just thought it was the same issue here. My apologies.

![image](https://user-images.githubusercontent.com/5675428/61404396-4b81b880-a8cf-11e9-9f1f-a508ca15b92c.png)

**Comment by aBo0oDyy** [comment]
If its ChatControl then you'll have to contact ChatControl.
And as i said, if the placeholder worked in PAPI's parse commnd, then its not PAPI issue and the placeholder is working fine.
