### ISSUE TITLE
[FR] %player_biome% placeholder returns unformatted text.

### ISSUE THREAD

**Issue by unsivilaudio** [PlaceholderAPI/Player-Expansion#30]
Can we get an supplementary placeholder that returns proper title text, e.g. "Warm Ocean" instead of "WARM_OCEAN".  I thought it might be useful information to display to my players on their scoreboard.  Yes I could just write a Js hook for this, but I feel it would increase server overhead, when the string could just as easily be formatted in papi.  Perhaps, just %player_biome_formatted% would be nice to have.  Thanks.

**Comment by Kqliber** [comment]
https://github.com/Kqliber/Player-Expansion/releases/tag/1.8.0 added in this release

**Comment by unsivilaudio** [comment]
Awesome, Thanks.
