### ISSUE TITLE
A Placeholder To Get The Player's Yaw & Pitch

### ISSUE THREAD

**Issue by NotGeri** [PlaceholderAPI/Player-Expansion#33]
Hey there.
I was wondering if it was possible to add a placeholder to get the parsed player's yaw and pitch (rotation). There is already a `%player_direction%` which returns the name of the cardinal direction (W/E/N/S) but it'd be much nicer to have the actual number. 

My idea is to simply have `%player_yaw%` and `%player_pitch%`.

Thanks for your consideration.

**Comment by Perzan** [comment]
I second this

**Comment by Kqliber** [comment]
https://github.com/Kqliber/Player-Expansion/releases/tag/1.8.0 added in this release.
