### ISSUE TITLE
%player_exp% not working correctly

### ISSUE THREAD

**Issue by hensih** [PlaceholderAPI/Player-Expansion#39]
%player_exp% returns 0.044944559 if the player has 86,438 experience

**Comment by DeadSteve51** [comment]
@hensih Is this still an issue?

**Comment by hensih** [comment]
Yes, this is still an issue.

**Comment by lucyy-mc** [comment]
AFAIK this works as intended. See org.bukkit.entity.Player#getExp(). OP, you may be looking for `%player_total_exp%`.

**Comment by BlitzOffline** [comment]
As lucyy stated, this works as intended. If you want exp points, you can look into the JS expansion and its Community Scripts: https://github.com/PlaceholderAPI/Javascript-Expansion/wiki/Community-Scripts#player-exp-points
