### ISSUE TITLE
Armor variables

### ISSUE THREAD

**Issue by pixar02** [PlaceholderAPI/Player-Expansion#4]
Could it be possible to add Armor variables?
Here are some examples:
Held items:
%player_mainhand_displayname% = Main hand's display-name 
%player_offhand_displayname% = Offhand's display-name 
%player_mainhand_durability% = Main hand's durability
%player_offhand_durability% = Offhand's durability

Armor slots:
%armor_helmet_displayname% = Helmet displayname
%armor_chestplate_displayname% = Chestplate displayname
%armor_leggings_displayname% = Leggings displayname
%armor_boots_displayname% = Boots displayname
%armor_helmet_durability% = Helmet's durability
%armor_chestplate_durability% = Chestplate's durability
%armor_leggings_durability% = Leggings' durability
%armor_boots_durability% = Boots' durability

Since these placeholders ares still based on the PLAYER I thougth adding them in this Expansion would be the best idea. Ofcourse these could be added in a seperate expansion. Just checking what would be better.
@extendedclip

**Comment by extendedclip** [comment]
I think these are a good idea. I don't have time rn but if you have time you can add them yourself.

**Comment by pixar02** [comment]
#6

**Comment by LemmoTresto** [comment]
Merged PR 025ab3814ced99c220b7c5eb591cd9c2c1a62427
