### ISSUE TITLE
can not register

### ISSUE THREAD

**Issue by cathats** [PlaceholderAPI/Player-Expansion#43]
placeholderAPI-2.10.10-dev-122 and placeholderAPI-2.10.9
mohist-1.16.5
Failed to register exoansion from PAPI-Expansion-Player.jar

**Comment by MakesYT** [comment]
I had the same problem
placeholderAPI-2.10.9 
mohist-1.16.5#370
PAPI-Expansion-Player.jar[1.7.2]
![image](https://user-images.githubusercontent.com/42534870/108870894-89120000-7633-11eb-9f12-acfb072aee1f.png)
![image](https://user-images.githubusercontent.com/42534870/108870901-89aa9680-7633-11eb-9c0d-ca79d3a0d28a.png)
![image](https://user-images.githubusercontent.com/42534870/108870904-8adbc380-7633-11eb-9d75-929c9be26f63.png)

**Comment by Dokman** [comment]
I can refer it to an open issue that i made with this error
https://github.com/Mohist-Community/Mohist/issues/1014

**Comment by Andre601** [comment]
Something I like to share is, that we recently (well... in the past 2 months or so) made a fix to address an issue where certain expansions would break the Loading process of PlaceholderAPI if the expansion in question was somehow malformed (i.e. didn't have a valid main class).

Following issues and PRs where made addressing that particular problem:)
- Issue https://github.com/PlaceholderAPI/PlaceholderAPI/issues/515
- Issue https://github.com/PlaceholderAPI/PlaceholderAPI/issues/516
- PR https://github.com/PlaceholderAPI/PlaceholderAPI/pull/517
- PR https://github.com/PlaceholderAPI/PlaceholderAPI/pull/530

Those things were also pushed to the master branch, so a Dev build should be available with those fixes. So please try this and let us know if that perhaps fixes this or any other issues you may have.

**Comment by Dokman** [comment]
I'll give you my log. I think mohist have some missgin features but it can be on other site i don't know.
[Log](https://haste.mohistmc.com/efococubip.yaml)

**Comment by darbyjack** [comment]
This should be fixed in the latest update. 

1) We don't directly support Mohist
2) They do some weird stuff with class loading that broke it
