### ISSUE TITLE
Failing to find the expansion

### ISSUE THREAD

**Issue by SubGplayz** [PlaceholderAPI/Player-Expansion#44]
when I try to download it, I get this message: Failed to find an expansion named: Player

**Comment by Warrior-of-San** [comment]
i`ve had the same problem for some time now, I also cant reload the plugin (seems like if it tries to connect to ecloud, but it cant), and none of the expansions (even when manually installing them, and restarting the server afterwards) dont work, only placeholders that are hard-coded into other plugins work. I tried different version - doesnt work. I tried disabling ecloud in the config - doesnt work. Tried removing all plugins that might interfere - doesnt work. Is the server down, was my ip blocked, or am i doing something wrong?

**Comment by darbyjack** [comment]
If you can't download from in-game you're more than welcome to use the site and manually download. https://api.extendedclip.com/home/
