### ISSUE TITLE
%player_ping% parsing error with 1.17

### ISSUE THREAD

**Issue by Intriguing-RC** [PlaceholderAPI/Player-Expansion#50]
There seems to be an error when parsing `%player_ping%`.

**Stacktrace:** https://paste.helpch.at/zanemobeve.java
**PlaceholderAPI Version:** 2.10.10-DEV
**Server Version:** 1.17

**Comment by VanillaChan6571** [comment]
Can confirm. I have a 96GB log file of just pure "java.lang.NoSuchFieldException: ping"

**Comment by darbyjack** [comment]
Thanks for letting us know. For now, just refrain from using the placeholder until we get a development jar out.

**Comment by Intriguing-RC** [comment]
Thanks a lot, the issue has been resolved.
