### ISSUE TITLE
Player expansion 2.0.1 lists as 2.0.0

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/Player-Expansion#56]
- Download Player expansion 2.0.1 = PAPI-Expansion-Player_i3C3hs6.jar
- Remove previous Player expansion in plugins/PlaceholderAPI/expansions/
- Install PAPI-Expansion-Player_i3C3hs6.jar in plugins/PlaceholderAPI/expansions/
- Execute `papi reload` (or restart server)
- Observe that papi list shows Player 2.0.0, out-of-date

**Comment by darbyjack** [comment]
Should be fixed via https://github.com/PlaceholderAPI/Player-Expansion/commit/473f637e0c0dafd54ccaf4439b7cf07ec2fd8af9

**Comment by SlimeDog** [comment]
It is. Thanks.
