### ISSUE TITLE
[Request] add %player_version%

### ISSUE THREAD

**Issue by parpar8090** [PlaceholderAPI/Player-Expansion#57]
please add %player_version% this will return the player's client version.

Here's a tutorial if needed:
https://www.spigotmc.org/threads/tutorial-getting-the-players-client-version.134397/

**Comment by darbyjack** [comment]
This could be added at some point in time but if you use ViaVersion, there's an expansion + placeholder that will return that for you if you don't want to wait for this to be added.

**Comment by parpar8090** [comment]
What is the expansion?

**Comment by darbyjack** [comment]
ViaVersion
