### ISSUE TITLE
Add a new placeholder

### ISSUE THREAD

**Issue by Clexus** [PlaceholderAPI/Player-Expansion#70]
%player_absorption%
with this method https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Damageable.html#getAbsorptionAmount()

**Comment by iGabyTM** [comment]
It already exists https://github.com/PlaceholderAPI/Player-Expansion/blob/dabc840d90f3edd2e8a555109de2a9f61cc97984/src/main/java/com/extendedclip/papi/expansion/player/PlayerExpansion.java#L226-L232
