### ISSUE TITLE
%player_online% error

### ISSUE THREAD

**Issue by ItzRonaldMLG** [PlaceholderAPI/Player-Expansion#76]
Type
Plugin Bug

What happens?
When using %parseother_{offline_player}_{player_online} returns an error and doesnt output a value.

Expected Behaviour
value "false"

How to Reproduce
Use the placeholder like this "%parseother_{offline_player}_{player_online}" or just %player_online%

/papi dump Output
https://paste.helpch.at/otimonecil

Console Log
https://pastebin.com/G4QRMMmx

Errors
No response

Additional Info
Im using this in another plugin, but every plugin i use this in this error keeps happening.
Even when the player is online the output will still have the error.

**Comment by Tanguygab** [comment]
this is not coming from the PlayerExpansion, nor from the ParseOther expansion but from the OfflineManager one which you're using in one of your DeluxeMenus menus
