### ISSUE TITLE
Player Locales stopped working in PaperMC 1.20.2

### ISSUE THREAD

**Issue by ShawnFoxter** [PlaceholderAPI/Player-Expansion#90]
all the placeholders related to Player Locale won't work on 1.20.2, even in a fresh server with only PAPI and Player Expansion

this is all what i get in console when parsing the locale
![image](https://github.com/PlaceholderAPI/Player-Expansion/assets/87722509/a9a03eb0-aa2f-48da-9b3d-7da8e0cc0d58)

**Comment by iGabyTM** [comment]
Dev note: `Player#getLocale` exists since [1.12](https://helpch.at/docs/1.12/org/bukkit/entity/Player.html#getLocale--)

**Comment by DicedDesigns** [comment]
Bumping this

**Comment by cj89898** [comment]
Fixed 56613e2
